<body class="position-relative login">
	<main class="position-absolute abs_center d-block p-4 ff-cg">
		<canvas id="cornerLines" class="l-0 t-0 w-100 h-100 position-absolute"></canvas>
		<img src="../public/img/logo.png" class="position-absolute abs_center t-0" alt="Logo">
		<h2 class="ff_Ms_bold text-center pb-2 text-white">Emailová autentifikácia</h2>
					<form action="" method="POST" name="login_form">
						<div class="form-group bord_b_2 row bg-white justify-content-center align-items-center mx-0 easy_rounded">
							<label for="checkString" class="col-3 col-sm-2 mb-0 color_ccc"><i class="fas fa-user"></i></label>
							<input type="text" name="checkString" required class="col-9 col-sm-10 px-1 form-control" id="checkString" placeholder="Vlož kód z tvojho emailu">
						</div>

						 <button type="submit" class="border-0 mb-2 text-light row mx-auto easy_rounded">Over a prihlás</button>
					</form>
	</main>
