<body class="position-relative admin">
  <div class="row h-100vh m-0">
    
  <?php   include_once '../resources/inc/_nav.php'; ?>

  <main class="col-12 col-md-11 font_w_reg offset-md-1 pt-4 pl-3">
    
    <div class="content font_Arial bg-white container pt-3 h-100">
      
      <div class="form-group bord_b_2 row mb-5 mx-0 bg-white justify-content-center align-items-center easy_rounded">
              <label for="searchQuery" class="mr-3 mb-0 color_ccc"><i class="fas fa-search"></i></label>
              <input type="text" name="searchQuery" class="col-auto col-sm-10 px-1 form-control" id="searchQuery" oninput="ajaxSearch(this)" placeholder="Zadaj hľadaný výraz">
      </div>
      <p>
        <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#searchFilters" aria-expanded="false" aria-controls="searchFilters">
          Filter
        </button>
      </p>
      <div class="collapse" id="searchFilters">
        <div class="card card-body">
          <form>
            <div class="form-group">
              <label for="status">Stav záznamu</label>
              <select class="form-control" id="status">
                <option>Pred inicializáciou</option>
                <option>Odoslaný inic. email</option>
                <option>Po 1. upozornení</option>
                <option>Po 2. upozornení</option>
                <option>Expirovaný</option>
              </select>
            </div>
            <div class="form-group">
              <label for="orderBy">Zoraď podľa</label>
              <select class="form-control" id="orderBy">
                <option>Priezviska investora A-Z</option>
                <option>Priezviska investora Z-A</option>
                <option>Dátumu od najnovších</option>
                <option>Dátumu od najstarších</option>
              </select>
            </div>
            <button class="btn btn-secondary" type="submit">
            Potvrď
            </button>
          </form>
        </div>
      </div>

  <?php 
  if (!empty($data["preparedData"])) { ?>   
  <div id="searchAnswer">
    Niečo máme    
  </div>    
<?php } else{ ?>
  <div class="row pt-2">
    <div class="col-12 text-center fw-bold ff-cg">
      Práve tu nie je žiadny obsah
    </div>
  </div>
  <?php } ?>
    </div>
  </main>
  </div>

