<button class="position-absolute t-0 l-0" data-toggle="modal" data-target="#newAcc"><i class="fas fa-plus"></i></button>
<form method="POST" class="col-6">
  <div class="form-group">
    <label for="email" class="fw-bold ff-cg my-2 col-12">Emailová adresa</label>
    <input type="email" required="" class="easy_rounded form-control" id="email" name="email" value="<?php echo $data["XML"] ?>">
  </div>
  <div class="form-group">
    <label for="pass" class="fw-bold ff-cg my-2 col-12">Heslo</label>
    <input type="password" required="" class="easy_rounded form-control" name="password" id="pass" placeholder="Heslo">
  </div>
  <div class="form-group" >
    <label for="confirmpwd" class="fw-bold ff-cg my-2 col-12">Potvrdenie hesla</label>
    <input type="password" required="" class="easy_rounded form-control" name="confirmpwd" id="confirmpwd" placeholder="Heslo">
  </div>
  <button type="button" class="my_button offset-4" onclick="regformhash(this.form,
                                   this.form.email,
                                   this.form.password,
                                   this.form.confirmpwd);" />Uložiť</button>  
  
</form>