<body class="position-relative admin">

	<div class="row h-100vh m-0 justify-content-center ">
		
	<?php 	include_once '../resources/inc/_nav.php'; ?>

	<main class="col-12 col-md-11 font_w_reg font_Arial offset-md-1 pl-3">
		<div class="row align-items-center justify-content-center h-100">
		<form action="" method="POST" class="col-4" enctype="multipart/form-data" name="update_form">
	<div class="form-group bord_b_2 row justify-content-center mx-0 mb-0">
		<input multiple="" type="file" name="updateFile[]" class="col-10 px-0 form-control" id="file" placeholder="Nahraj aktualizovaný súbor" aria-describedby="uplhelp" style="display: none">
		<label for="file" class="text-center border bg-light col-12 mb-0 color_ccc easy_rounded">
		Zde DragNDrop raz bude státi!
		</label>
		<small id="uplHelp" class="form-text text-muted">Povolený formát - XLSX</small>
	</div>
	<div class="row m-0 mt-3 justify-content-center align-items-center">
		<button type="submit" class="my_button btn">Odošli</button>
	</div>
</form>
</div>
	</main>
	</div>